version: '3.4'

services:
  catalogdb:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  weather.microservice1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://ForecastDb:27017"
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro